apiVersion: 1

datasources:
  - name: InfluxDB-Set
    uid: c044bdfd-5bfa-4af9-af88-98655c5a9e59
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: Set2
      tlsSkipVerify: false
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
